project_name: "SyncTrack_total_generation"
log_directory: "logs"
mode: test #validate_and_train
dev: False

id:
  version: "slakh2100"
  name: "pretrained_model"

trainer:
  validation_every_n_steps:  
  save_checkpoint_every_n_steps:
  save_top_k: 2
  max_epochs: 1200
  limit_train_batches: 
  limit_val_batches: 221
  resume: 
  resume_from_checkpoint: 
  accelerator: gpu
  precision: 32
  devices: 
    - 4
    # - 0
    # - 1
    # - 2



data:
  target: src.utilities.data.datamodule.DataModuleFromConfig
  params:
    batch_size: 16 #16
    num_workers: 2 #8

    augmentation:
      mixup: 0.0
      return_all_wav: False
      balanced_sampling: False
      masking: False

    path:
      dataset_type: "MultiSource_Slakh"
      train_data:
        - /path/to/slakh2100/train
        - /path/to/slakh2100/validation
      valid_data: /path/to/slakh2100/test
      test_data: 
      label_data: 
      tempo_data: ""
      tempo_map: ""
      stems: 
        - 'bass'
        - 'drums'
        - 'guitar'
        - 'piano'
      shuffle_val_test: False


    preprocessing:
      label:
        norm: True
        top_k: 527
        quantization: False
        threshold: 0.01
        label_use_original_ground_truth: False
      audio:
        sampling_rate: 16000
        max_wav_value: 32768.0
      stft:
        filter_length: 1024
        hop_length: 160
        win_length: 1024
      mel:
        n_mel_channels: 64
        mel_fmin: 0
        mel_fmax: 8000
        freqm: 0
        timem: 0
        blur: False
        target_length: 1024

model:
  target: latent_diffusion.models.synctrack_eval.MusicLDM
  params:
    num_stems: 4
    base_learning_rate: 3.0e-05
    batchsize: 45
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: fbank_stems
    cond_stage_key: fbank 
    latent_t_size: 256 
    latent_f_size: 16 
    channels: 8 
    cond_stage_trainable: False
    latent_mixup: 0.0
    conditioning_key: concat
    monitor: val/loss_simple_ema 
    scale_by_std: true
    seperate_stem_z: False
    use_silence_weight: False
    tau: 2.0
    ckpt_path: ckpt/synctrack_slakh2100_pretrained.ckpt
    unet_config:
      target: latent_diffusion.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64 
        in_channels: 8
        out_channels: 8 
        model_channels: 128 
        no_condition: false
        dims: 2
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_head_channels: 32
        use_spatial_transformer: true 
    first_stage_config:
      base_learning_rate: 4.5e-05
      target: latent_encoder.autoencoder.AutoencoderKL
      params: 
        reload_from_ckpt: ckpt/vae-ckpt.ckpt
        batchsize: 4
        monitor: val/rec_loss
        image_key: fbank
        subband: 1
        embed_dim: 8 
        time_shuffle: 1
        mel_num: 64 
        lossconfig:
          target: latent_diffusion.modules.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1.0
            disc_weight: 0.5
            disc_in_channels: 1
        ddconfig:
          double_z: true
          hifigan_ckpt: ckpt/hifigan-ckpt.ckpt
          z_channels: 8 
          resolution: 256
          downsample_time: false
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0



    cond_stage_config:
      target: latent_diffusion.modules.encoders.modules.Patch_Cond_Model
      params:
        sampling_rate: 16000
        embed_mode: fbank
        unconditional_prob: 0.0
        

        

    evaluation_params:
      unconditional_guidance_scale: 0.0
      ddim_sampling_steps: 200
      n_candidates_per_samples: 1
      